[2025-03-22 20:39:20,774 I 1956275 1956275] (raylet) main.cc:219: Setting cluster ID to: 64e402b5f7a3d17f64dd0460fbea24fb473f73e1ece759888379d005
[2025-03-22 20:39:20,784 I 1956275 1956275] (raylet) main.cc:334: Raylet is not set to kill unknown children.
[2025-03-22 20:39:20,785 I 1956275 1956275] (raylet) io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2025-03-22 20:39:20,786 I 1956275 1956275] (raylet) main.cc:464: Setting node ID node_id=d6c24439951b078c9377d97368c89d3fc558155e1d1d733f224bc185
[2025-03-22 20:39:20,787 I 1956275 1956275] (raylet) store_runner.cc:51: Allowing the Plasma store to use up to 1.9122GB of memory.
[2025-03-22 20:39:20,787 I 1956275 1956275] (raylet) store_runner.cc:67: Starting object store with directory /dev/shm, fallback C:\Users\11260\AppData\Local\Temp\ray, and huge page support disabled
[2025-03-22 20:39:20,790 I 1956275 1956306] (raylet) dlmalloc.cc:153: create_and_mmap_buffer(1912209416, /dev/shm/plasmaXXXXXX)
[2025-03-22 20:39:20,791 W 1956275 1956306] (raylet) file_system_monitor.cc:59: Failed to get capacity of C:\Users\11260\AppData\Local\Temp\ray\session_2025-03-22_19-41-25_494699_4860 with error: No such file or directory
[2025-03-22 20:39:20,791 E 1956275 1956306] (raylet) logging.cc:113: Unhandled exception: N5boost10wrapexceptINS_6system12system_errorEEE. what(): Invalid argument [system:22]
[2025-03-22 20:39:20,798 E 1956275 1956275] (raylet) logging.cc:113: Unhandled exception: N5boost10wrapexceptINS_6system12system_errorEEE. what(): Invalid argument [system:22]
[2025-03-22 20:39:20,802 E 1956275 1956306] (raylet) logging.cc:120: Stack trace: 
 /root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb3cea) [0x55dec947bcea] ray::operator<<()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb6c02) [0x55dec947ec02] ray::TerminateHandler()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da) [0x7f5aa6bd70da]
/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7f5aa6bc1a55] std::unexpected()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb391) [0x7f5aa6bd7391]
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb5f6) [0x55dec88b35f6] boost::throw_exception<>()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb63b) [0x55dec88b363b] boost::asio::detail::do_throw_error()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c24) [0x55dec948bc24] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c45) [0x55dec948bc45] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xda8664) [0x55dec9470664] ParseUrlEndpoint()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x44acee) [0x55dec8b12cee] plasma::PlasmaStore::PlasmaStore()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x441c84) [0x55dec8b09c84] plasma::PlasmaStoreRunner::Start()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4029f5) [0x55dec8aca9f5] std::thread::_State_impl<>::_M_run()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xe0b820) [0x55dec94d3820] execute_native_thread_routine
/lib/x86_64-linux-gnu/libc.so.6(+0x9caa4) [0x7f5aa6976aa4]
/lib/x86_64-linux-gnu/libc.so.6(+0x129c3c) [0x7f5aa6a03c3c]

[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497: *** SIGABRT received at time=1742647160 on cpu 4 ***
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497: PC: @     0x7f5aa6978b2c  (unknown)  pthread_kill
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa691f330       1536  (unknown)
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa691f27e         32  raise
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa69028ff        192  abort
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec947ebda       1184  ray::TerminateHandler()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa6bd70da         16  (unknown)
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa6bc1a55         16  std::terminate()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x7f5aa6bd7391         48  __cxa_throw
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec88b35f6         48  boost::throw_exception<>()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec88b363b        112  boost::asio::detail::do_throw_error()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec948bc24         96  boost::asio::ip::make_address()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec948bc45         32  boost::asio::ip::make_address()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec9470664       1584  ParseUrlEndpoint()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec8b12cee        400  plasma::PlasmaStore::PlasmaStore()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec8b09c84       1456  plasma::PlasmaStoreRunner::Start()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec8aca9f5        208  std::thread::_State_impl<>::_M_run()
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @     0x55dec94d3820  256433632  execute_native_thread_routine
[2025-03-22 20:39:20,807 E 1956275 1956306] (raylet) logging.cc:497:     @ ... and at least 3 more frames
