[2025-03-22 20:12:26,113 I 1950993 1950993] (raylet) main.cc:219: Setting cluster ID to: 64e402b5f7a3d17f64dd0460fbea24fb473f73e1ece759888379d005
[2025-03-22 20:12:26,123 I 1950993 1950993] (raylet) main.cc:334: Raylet is not set to kill unknown children.
[2025-03-22 20:12:26,123 I 1950993 1950993] (raylet) io_service_pool.cc:35: IOServicePool is running with 1 io_service.
[2025-03-22 20:12:26,125 I 1950993 1950993] (raylet) main.cc:464: Setting node ID node_id=ae2eb4dae4dfc703e763f4c114599c1687149dd012e22581a990c4ec
[2025-03-22 20:12:26,125 I 1950993 1950993] (raylet) store_runner.cc:51: Allowing the Plasma store to use up to 2.04109GB of memory.
[2025-03-22 20:12:26,125 I 1950993 1950993] (raylet) store_runner.cc:67: Starting object store with directory /dev/shm, fallback C:\Users\11260\AppData\Local\Temp\ray, and huge page support disabled
[2025-03-22 20:12:26,129 I 1950993 1951024] (raylet) dlmalloc.cc:153: create_and_mmap_buffer(2041184264, /dev/shm/plasmaXXXXXX)
[2025-03-22 20:12:26,130 W 1950993 1951024] (raylet) file_system_monitor.cc:59: Failed to get capacity of C:\Users\11260\AppData\Local\Temp\ray\session_2025-03-22_19-41-25_494699_4860 with error: No such file or directory
[2025-03-22 20:12:26,145 E 1950993 1950993] (raylet) logging.cc:113: Unhandled exception: N5boost10wrapexceptINS_6system12system_errorEEE. what(): Invalid argument [system:22]
[2025-03-22 20:12:26,145 E 1950993 1951024] (raylet) logging.cc:113: Unhandled exception: N5boost10wrapexceptINS_6system12system_errorEEE. what(): Invalid argument [system:22]
[2025-03-22 20:12:26,153 E 1950993 1951024] (raylet) logging.cc:120: Stack trace: 
 /root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb3cea) [0x556c359bacea] ray::operator<<()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb6c02) [0x556c359bdc02] ray::TerminateHandler()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da) [0x7f54b724f0da]
/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7f54b7239a55] std::unexpected()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb391) [0x7f54b724f391]
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb5f6) [0x556c34df25f6] boost::throw_exception<>()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb63b) [0x556c34df263b] boost::asio::detail::do_throw_error()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c24) [0x556c359cac24] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c45) [0x556c359cac45] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xda8664) [0x556c359af664] ParseUrlEndpoint()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x44acee) [0x556c35051cee] plasma::PlasmaStore::PlasmaStore()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x441c84) [0x556c35048c84] plasma::PlasmaStoreRunner::Start()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4029f5) [0x556c350099f5] std::thread::_State_impl<>::_M_run()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xe0b820) [0x556c35a12820] execute_native_thread_routine
/lib/x86_64-linux-gnu/libc.so.6(+0x9caa4) [0x7f54b6feeaa4]
/lib/x86_64-linux-gnu/libc.so.6(+0x129c3c) [0x7f54b707bc3c]

[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497: *** SIGABRT received at time=1742645546 on cpu 31 ***
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497: PC: @     0x7f54b6ff0b2c  (unknown)  pthread_kill
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b6f97330       1536  (unknown)
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b6f9727e         32  raise
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b6f7a8ff        192  abort
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c359bdbda       1184  ray::TerminateHandler()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b724f0da         16  (unknown)
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b7239a55         16  std::terminate()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x7f54b724f391         48  __cxa_throw
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c34df25f6         48  boost::throw_exception<>()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c34df263b        112  boost::asio::detail::do_throw_error()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c359cac24         96  boost::asio::ip::make_address()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c359cac45         32  boost::asio::ip::make_address()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c359af664       1584  ParseUrlEndpoint()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c35051cee        400  plasma::PlasmaStore::PlasmaStore()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c35048c84       1456  plasma::PlasmaStoreRunner::Start()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c350099f5        208  std::thread::_State_impl<>::_M_run()
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @     0x556c35a12820  256433632  execute_native_thread_routine
[2025-03-22 20:12:26,159 E 1950993 1951024] (raylet) logging.cc:497:     @ ... and at least 3 more frames
[2025-03-22 20:12:26,162 E 1950993 1950993] (raylet) logging.cc:120: Stack trace: 
 /root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb3cea) [0x556c359bacea] ray::operator<<()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdb6c02) [0x556c359bdc02] ray::TerminateHandler()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb0da) [0x7f54b724f0da]
/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7f54b7239a55] std::unexpected()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbb391) [0x7f54b724f391]
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb5f6) [0x556c34df25f6] boost::throw_exception<>()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1eb63b) [0x556c34df263b] boost::asio::detail::do_throw_error()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c24) [0x556c359cac24] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3c45) [0x556c359cac45] boost::asio::ip::make_address()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xda8664) [0x556c359af664] ParseUrlEndpoint()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x69f9e3) [0x556c352a69e3] ray::ConnectSocketRetry()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x487534) [0x556c3508e534] plasma::PlasmaClient::Impl::Connect()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4878e6) [0x556c3508e8e6] plasma::PlasmaClient::Connect()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4201ce) [0x556c350271ce] ray::ObjectManager::ObjectManager()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x330790) [0x556c34f37790] ray::raylet::NodeManager::NodeManager()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x35f991) [0x556c34f66991] ray::raylet::Raylet::Raylet()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x27ab31) [0x556c34e81b31] main::{lambda()#5}::operator()()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x27c329) [0x556c34e83329] std::_Function_handler<>::_M_invoke()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4f6aea) [0x556c350fdaea] ray::gcs::InternalKVAccessor::AsyncGetInternalConfig()::{lambda()#1}::operator()()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4eb238) [0x556c350f2238] std::_Function_handler<>::_M_invoke()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4fbc6d) [0x556c35102c6d] std::_Function_handler<>::_M_invoke()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x4ede55) [0x556c350f4e55] ray::rpc::ClientCallImpl<>::OnReplyReceived()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x2a6865) [0x556c34ead865] std::_Function_handler<>::_M_invoke()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x6f5aa8) [0x556c352fcaa8] EventTracker::RecordExecution()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x6f0a9e) [0x556c352f7a9e] std::_Function_handler<>::_M_invoke()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x6f0f16) [0x556c352f7f16] boost::asio::detail::completion_handler<>::do_complete()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc105b) [0x556c359c805b] boost::asio::detail::scheduler::do_run_one()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc35e9) [0x556c359ca5e9] boost::asio::detail::scheduler::run()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0xdc3b02) [0x556c359cab02] boost::asio::io_context::run()
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x1f2427) [0x556c34df9427] main
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x7f54b6f7c1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f54b6f7c28b] __libc_start_main
/root/anaconda3/envs/p2pray/lib/python3.12/site-packages/ray/core/src/ray/raylet/raylet(+0x24b957) [0x556c34e52957]

